In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/processed/master_zomato.csv"
)

In [2]:
df["votes_norm"] = (
    df["votes"] - df["votes"].min()
) / (
    df["votes"].max() - df["votes"].min()
)

In [3]:
df["online_order_num"] = (
    df["online_order"] == "Yes"
).astype(int)

df["book_table_num"] = (
    df["book_table"] == "Yes"
).astype(int)

In [4]:
df["success_score"] = (
    0.5 * df["rate"].fillna(df["rate"].median())
    +
    0.3 * df["votes_norm"]
    +
    0.1 * df["online_order_num"]
    +
    0.1 * df["book_table_num"]
)

In [5]:
df[
    ["name",
     "location",
     "rate",
     "votes",
     "success_score"]
].sort_values(
    "success_score",
    ascending=False
).head(20)

,name,location,rate,votes,success_score
2236,Byg Brewski Brewing Company,Sarjapur Road,4.9,16345,2.950000
10839,AB's - Absolute Barbecues,Marathahalli,4.8,12121,2.722472
10264,Chili's American Grill & Bar,Malleshwaram,4.8,6433,2.718073
4900,Asia Kitchen By Mainland China,Koramangala 5th Block,4.9,2178,2.689976
10277,Punjab Grill,Malleshwaram,4.9,1940,2.685607
4889,AB's - Absolute Barbecues,BTM,4.9,6375,2.667008
4166,Brew and Barbeque - A Microbrewery Pub,Marathahalli,4.7,5746,2.655463
4895,The Black Pearl,Koramangala 5th Block,4.7,10413,2.641123
2979,Hammered,Cunningham Road,4.7,4639,2.635145
8267,The Pizza Bakery,Indiranagar,4.8,1724,2.631643
2082,The Black Pearl,Marathahalli,4.8,7023,2.628902
8510,Toit,Indiranagar,4.7,14956,2.624506
4937,Truffles,Koramangala 5th Block,4.7,14654,2.618963
7912,Big Pitcher,Old Airport Road,4.7,9021,2.615574
3906,Flechazo,Whitefield,4.9,2745,2.600382
8061,Smoke House Deli,Indiranagar,4.6,5421,2.599498
11116,The Boozy Griffin,Marathahalli,4.8,4696,2.586191
3026,Belgian Waffle Factory,Brigade Road,4.9,1746,2.582046
10841,Flechazo,Marathahalli,4.7,7154,2.581306
7913,Barbeque Nation,Indiranagar,4.7,7152,2.581270

In [6]:
df.sort_values(
    "success_score",
    ascending=False
).head(10)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,...,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),votes_norm,online_order_num,book_table_num,success_score
2236,https://www.zomato.com/bangalore/byg-brewski-b...,"Behind MK Retail, Sarjapur Road, Bangalore",Byg Brewski Brewing Company,Yes,Yes,4.9,16345,+91 8039514766,Sarjapur Road,Microbrewery,...,"Continental, North Indian, Italian, South Indi...",1600.0,"[('Rated 5.0', 'RATED\n I have been to this p...",[],Delivery,Bellandur,1.000000,1,1,2.950000
10839,https://www.zomato.com/bangalore/abs-absolute-...,"90/4, 3rd Floor, Outer Ring Road, Munnekollaly...",AB's - Absolute Barbecues,No,Yes,4.8,12121,080 49652574,Marathahalli,Casual Dining,...,"European, Mediterranean, North Indian, BBQ",1600.0,"[('Rated 4.0', 'RATED\n We came here for a te...",[],Buffet,Marathahalli,0.741572,0,1,2.722472
10264,https://www.zomato.com/bangalore/chilis-americ...,"2nd Floor, Orion Mall, Dr. Rajkumar Road, Mall...",Chili's American Grill & Bar,Yes,Yes,4.8,6433,+91 9500075479\n+91 9535541956,Malleshwaram,"Casual Dining, Bar",...,"American, Tex-Mex, Burger, BBQ, Mexican",1400.0,"[('Rated 2.0', ""RATED\n Pricey menu for the q...","['Bacon Ranch Chicken Quesadillas', 'Onion Rin...",Delivery,Malleshwaram,0.393576,1,1,2.718073
4900,https://www.zomato.com/bangalore/asia-kitchen-...,"136, Ground Floor, 1st Cross, 5th Block, Jyoti...",Asia Kitchen By Mainland China,Yes,Yes,4.9,2178,080 49652573,Koramangala 5th Block,"Casual Dining, Bar",...,"Asian, Chinese, Thai, Momos",1500.0,"[('Rated 5.0', ""RATED\n This is not just one ...",[],Buffet,BTM,0.133252,1,1,2.689976
10277,https://www.zomato.com/bangalore/punjab-grill-...,"26/1, Dr Rajkumar Road, Brigade Gateway Campus...",Punjab Grill,Yes,Yes,4.9,1940,+91 8022682400,Malleshwaram,Casual Dining,...,"North Indian, Mughlai",2000.0,"[('Rated 5.0', 'RATED\n One of the best place...","['Fish Amritsari', 'Murgh Fatehwal', 'Nalli Go...",Delivery,Malleshwaram,0.118691,1,1,2.685607
4889,https://www.zomato.com/bangalore/abs-absolute-...,"100 Feet Road, 1st Phase, Near Jayadeva Flyove...",AB's - Absolute Barbecues,No,Yes,4.9,6375,040 45659912,BTM,Casual Dining,...,"European, Mediterranean, North Indian, BBQ",1600.0,"[('Rated 5.0', 'RATED\n We liked the place a ...",[],Buffet,BTM,0.390028,0,1,2.667008
4166,https://www.zomato.com/bangalore/brew-and-barb...,"36/4, Fourth Floor, Soul Space Arena, Outer Ri...",Brew and Barbeque - A Microbrewery Pub,Yes,Yes,4.7,5746,080 45128649,Marathahalli,"Microbrewery, Pub",...,"Continental, North Indian, BBQ, Steak",1400.0,"[('Rated 5.0', ""RATED\n A day at brew and bar...","['Mushroom Orley', 'Tandoori Sarsonwali Phool'...",Delivery,Brookefield,0.351545,1,1,2.655463
4895,https://www.zomato.com/bangalore/the-black-pea...,"105, 1st A Cross Road, Jyothi Nivas College Ro...",The Black Pearl,No,Yes,4.7,10413,080 49652452,Koramangala 5th Block,"Casual Dining, Bar",...,"North Indian, European, Mediterranean",1400.0,"[('Rated 1.0', ""RATED\n FOOD\nThe buffet was ...",[],Buffet,BTM,0.637076,0,1,2.641123
2979,https://www.zomato.com/bangalore/hammered-cunn...,"18, Ali Askar Road, Cunningham Road, Bangalore",Hammered,Yes,Yes,4.7,4639,+91 8041217527\r\n+91 7618729481,Cunningham Road,"Pub, Cafe",...,"North Indian, Thai, Japanese, Continental, Cafe",1300.0,"[('Rated 5.0', ""RATED\n We visited during aft...",[],Cafes,Brigade Road,0.283818,1,1,2.635145
8267,https://www.zomato.com/bangalore/the-pizza-bak...,"2985, 12th Main, HAL 2nd Stage, Indiranagar, B...",The Pizza Bakery,Yes,Yes,4.8,1724,080 49652968,Indiranagar,Casual Dining,...,"Italian, Pizza, Beverages",1200.0,"[('Rated 3.0', ""RATED\n Their garlic bread ta...",[],Delivery,Indiranagar,0.105476,1,1,2.631643

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/processed/master_zomato.csv"
)

df.shape

(12435, 17)

In [8]:
df["votes_norm"] = (
    df["votes"] - df["votes"].min()
) / (
    df["votes"].max() - df["votes"].min()
)

In [9]:
df["online_order_num"] = (
    df["online_order"] == "Yes"
).astype(int)

In [10]:
df["book_table_num"] = (
    df["book_table"] == "Yes"
).astype(int)

In [11]:
df["success_score"] = (
    0.5 * df["rate"].fillna(df["rate"].median())
    +
    0.3 * df["votes_norm"]
    +
    0.1 * df["online_order_num"]
    +
    0.1 * df["book_table_num"]
)

In [12]:
df[
    [
        "name",
        "rate",
        "votes",
        "success_score"
    ]
].head()

                    name  rate  votes  success_score
0                  Jalsa   4.1    775       2.264225
1         Spice Elephant   4.1    787       2.164445
2        San Churro Cafe   3.8    918       2.016849
3  Addhuri Udupi Bhojana   3.7     88       1.851615
4          Grand Village   3.8    166       1.903047

In [13]:
df.to_csv(
    "../data/processed/final_zomato.csv",
    index=False
)

print("Final dataset saved!")

Final dataset saved!